import Link from "next/link";
import { Search } from "lucide-react";
import { AgentCard } from "@/components/agent-card";
import { AiSearchButton } from "@/components/ai-search-modal";
import { NoriaMark } from "@/components/noria-mark";
import { getAgents } from "@/lib/8004scan";
import { explainMatch, rankAgents } from "@/lib/ranking";

export default async function Discover({searchParams}:{searchParams:Promise<{q?:string}>}){const params=await searchParams;const query=(params.q?.trim()??"").slice(0,200);const result=await getAgents({query:query||undefined,limit:40}).catch(()=>({success:false,data:[],meta:undefined}));const ranked=query?rankAgents(result.data,{rawQuery:query}):result.data.map(agent=>({agent,relevance:undefined}));return <main className="min-h-screen bg-[#f5f2ff] px-4 pb-36 pt-5 text-[#111] sm:px-8 lg:px-12"><div className="noria-scale mx-auto max-w-[1160px]"><header className="flex items-center justify-between rounded-full bg-[#f3f5f8] p-2 pl-4"><Link href="/" className="flex items-center gap-3 font-semibold"><span className="flex size-10 items-center justify-center rounded-full bg-[#7048ed] text-white"><NoriaMark className="size-5"/></span>Noria</Link><AiSearchButton/></header><section className="pb-12 pt-20 sm:pt-28"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#7048ed]">AI directory</p><h1 className="mt-5 max-w-4xl font-editorial text-6xl leading-[.88] tracking-[-.055em] sm:text-8xl">{query?`Agents for “${query}”`:"Find the AI that fits the job."}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-black/50">Search the live BSC index. We show what each agent has published and link back to the source.</p><form action="/discover" className="mt-10 flex max-w-3xl items-center rounded-full bg-[#f3f5f8] p-2"><Search className="ml-4 size-5 text-black/30"/><label htmlFor="agent-search" className="sr-only">Search agents</label><input id="agent-search" defaultValue={query} name="q" placeholder="Try “yield”, “Venus” or “monitoring”" className="min-h-12 min-w-0 flex-1 bg-transparent px-4 text-sm outline-none placeholder:text-black/30"/><button className="rounded-full bg-[#111] px-6 py-3 text-sm font-semibold text-white transition hover:bg-[#7048ed]">Search</button></form></section><div className="mb-5 flex items-center justify-between text-xs text-black/40"><span>{ranked.length} records</span><span>BSC · chain 56</span></div>{!result.success?<div className="rounded-[26px] bg-[#fff3e8] p-7 text-sm text-[#8b4e17]">The agent source is having trouble. Try again in a moment.</div>:ranked.length?<div className="space-y-3">{ranked.map(({agent,relevance})=><AgentCard key={agent.id} agent={agent} relevance={relevance} matchReason={query?explainMatch(agent,{rawQuery:query}):undefined}/>)}</div>:<div className="rounded-[26px] bg-[#f3f5f8] p-8 text-sm text-black/50">Nothing matched that search. Try a protocol name or a broader task.</div>}</div></main>}
