"use client";
import * as React from "react";
import useEmblaCarousel, { type UseEmblaCarouselType } from "embla-carousel-react";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";

type CarouselApi=UseEmblaCarouselType[1];
type CarouselProps={opts?:Parameters<typeof useEmblaCarousel>[0];plugins?:Parameters<typeof useEmblaCarousel>[1];orientation?:"horizontal"|"vertical";setApi?:(api:CarouselApi)=>void};
type Ctx=CarouselProps&{carouselRef:ReturnType<typeof useEmblaCarousel>[0];api:CarouselApi;scrollPrev:()=>void;scrollNext:()=>void;canScrollPrev:boolean;canScrollNext:boolean};
const Context=React.createContext<Ctx|null>(null);
function useCarousel(){const c=React.useContext(Context);if(!c)throw new Error("useCarousel must be used within Carousel");return c;}
const Carousel=React.forwardRef<HTMLDivElement,React.HTMLAttributes<HTMLDivElement>&CarouselProps>(({orientation="horizontal",opts,setApi,plugins,className,children,...props},ref)=>{const[carouselRef,api]=useEmblaCarousel({...opts,axis:orientation==="horizontal"?"x":"y"},plugins);const[canScrollPrev,setPrev]=React.useState(false);const[canScrollNext,setNext]=React.useState(false);const onSelect=React.useCallback((a:CarouselApi)=>{if(a){setPrev(a.canScrollPrev());setNext(a.canScrollNext());}},[]);const scrollPrev=React.useCallback(()=>api?.scrollPrev(),[api]);const scrollNext=React.useCallback(()=>api?.scrollNext(),[api]);React.useEffect(()=>{if(api&&setApi)setApi(api)},[api,setApi]);React.useEffect(()=>{if(!api)return;const initial=window.setTimeout(()=>onSelect(api),0);api.on("reInit",onSelect);api.on("select",onSelect);return()=>{window.clearTimeout(initial);api.off("select",onSelect)}},[api,onSelect]);return <Context.Provider value={{carouselRef,api,opts,orientation,setApi,plugins,scrollPrev,scrollNext,canScrollPrev,canScrollNext}}><div ref={ref} className={cn("relative",className)} role="region" aria-roledescription="carousel" {...props}>{children}</div></Context.Provider>});Carousel.displayName="Carousel";
const CarouselContent=React.forwardRef<HTMLDivElement,React.HTMLAttributes<HTMLDivElement>>(({className,...props},ref)=>{const{carouselRef,orientation}=useCarousel();return <div ref={carouselRef} className="overflow-hidden"><div ref={ref} className={cn("flex",orientation==="horizontal"?"-ml-4":"-mt-4 flex-col",className)} {...props}/></div>});CarouselContent.displayName="CarouselContent";
const CarouselItem=React.forwardRef<HTMLDivElement,React.HTMLAttributes<HTMLDivElement>>(({className,...props},ref)=>{const{orientation}=useCarousel();return <div ref={ref} role="group" aria-roledescription="slide" className={cn("min-w-0 shrink-0 grow-0 basis-full",orientation==="horizontal"?"pl-4":"pt-4",className)} {...props}/>});CarouselItem.displayName="CarouselItem";
const CarouselPrevious=React.forwardRef<HTMLButtonElement,React.ComponentProps<typeof Button>>(({className,...props},ref)=>{const{scrollPrev,canScrollPrev}=useCarousel();return <Button ref={ref} size="icon" variant="outline" className={cn("rounded-full",className)} disabled={!canScrollPrev} onClick={scrollPrev} {...props}><ArrowLeft className="size-4"/><span className="sr-only">Previous slide</span></Button>});CarouselPrevious.displayName="CarouselPrevious";
const CarouselNext=React.forwardRef<HTMLButtonElement,React.ComponentProps<typeof Button>>(({className,...props},ref)=>{const{scrollNext,canScrollNext}=useCarousel();return <Button ref={ref} size="icon" variant="outline" className={cn("rounded-full",className)} disabled={!canScrollNext} onClick={scrollNext} {...props}><ArrowRight className="size-4"/><span className="sr-only">Next slide</span></Button>});CarouselNext.displayName="CarouselNext";
export{type CarouselApi,Carousel,CarouselContent,CarouselItem,CarouselPrevious,CarouselNext};
