"use client";
import Image from "next/image";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Carousel, type CarouselApi, CarouselContent, CarouselItem } from "@/components/ui/carousel";

export interface Gallery4Item{id:string;title:string;description:string;href:string;image:string;eyebrow?:string}
export function Gallery4({title="Look closer",description="Open any agent to see what it has actually published.",items}:{title?:string;description?:string;items:Gallery4Item[]}){const[api,setApi]=useState<CarouselApi>();const[prev,setPrev]=useState(false);const[next,setNext]=useState(false);const[current,setCurrent]=useState(0);useEffect(()=>{if(!api)return;const update=()=>{setPrev(api.canScrollPrev());setNext(api.canScrollNext());setCurrent(api.selectedScrollSnap())};const initial=window.setTimeout(update,0);api.on("select",update);api.on("reInit",update);return()=>{window.clearTimeout(initial);api.off("select",update)}},[api]);return <section className="bg-white py-24 sm:py-32"><div className="mx-auto mb-10 flex max-w-[1120px] items-end justify-between gap-5 px-5 sm:px-8"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#2864ff]">Agent directory</p><h2 className="mt-4 font-editorial text-6xl tracking-[-.05em] text-[#111] sm:text-8xl">{title}</h2><p className="mt-4 max-w-xl text-base leading-7 text-black/50">{description}</p></div><div className="hidden gap-2 md:flex"><Button size="icon" variant="outline" onClick={()=>api?.scrollPrev()} disabled={!prev}><ArrowLeft className="size-5"/></Button><Button size="icon" variant="outline" onClick={()=>api?.scrollNext()} disabled={!next}><ArrowRight className="size-5"/></Button></div></div><Carousel setApi={setApi} opts={{align:"start",dragFree:true}}><CarouselContent className="ml-0 pl-[max(20px,calc((100vw-1120px)/2))] pr-5"><>{items.map((item)=><CarouselItem key={item.id} className="max-w-[310px] pl-4 sm:max-w-[380px]"><a href={item.href} className="group block overflow-hidden rounded-[30px]"><div className="relative min-h-[440px] overflow-hidden rounded-[30px]"><Image src={item.image} alt="" fill unoptimized sizes="(max-width: 640px) 310px, 380px" className="object-cover transition-transform duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/20 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7 text-white"><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-white/60">{item.eyebrow||"Indexed agent"}</p><h3 className="mt-3 text-2xl font-semibold tracking-[-.035em]">{item.title}</h3><p className="mt-3 line-clamp-2 text-sm leading-6 text-white/68">{item.description}</p><div className="mt-8 flex items-center text-sm font-semibold">Open agent <ArrowRight className="ml-2 size-5 transition-transform group-hover:translate-x-1"/></div></div></div></a></CarouselItem>)}</></CarouselContent></Carousel><div className="mt-8 flex justify-center gap-2">{items.map((_,index)=><button key={index} className={`size-2 rounded-full transition-colors ${current===index?"bg-[#2864ff]":"bg-[#2864ff]/20"}`} onClick={()=>api?.scrollTo(index)} aria-label={`Go to slide ${index+1}`}/>)}</div></section>}
