"use client";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight,Database,Network,ShieldCheck } from "lucide-react";
import { useEffect } from "react";
import { motion,stagger,useAnimate,useReducedMotion } from "motion/react";
import { NoriaMark } from "@/components/noria-mark";

export function MinimalHero({total}:{total?:number}){const[scope,animate]=useAnimate();const reduceMotion=useReducedMotion();useEffect(()=>{if(reduceMotion)return;animate(".hero-reveal",{opacity:[0,1],y:[24,0],filter:["blur(8px)","blur(0px)"]},{duration:.8,delay:stagger(.12),ease:[.16,1,.3,1]})},[animate,reduceMotion]);return <section className="relative min-h-screen overflow-hidden bg-white"><div className="absolute inset-0 h-[68%] overflow-hidden grayscale">{reduceMotion?<Image src="/noria-hero-poster.jpg" alt="" fill priority className="object-cover [transform:scaleY(-1)]"/>:<video autoPlay loop muted playsInline className="h-full w-full object-cover [transform:scaleY(-1)]" src="/noria-hero-bg.mp4"/>}<div className="absolute inset-0 bg-gradient-to-b from-[26.416%] from-[rgba(255,255,255,0)] to-[66.943%] to-white"/></div><motion.div ref={scope} className="relative mx-auto flex max-w-[1200px] flex-col items-start gap-8 px-5 pb-28 pt-[290px] text-left sm:px-8"><motion.h1 className="hero-reveal max-w-[1060px] text-balance text-[52px] font-medium leading-[.9] tracking-[-.04em] text-[#111] sm:text-[64px] lg:text-[80px]">The <span className="font-instrument text-[64px] font-normal italic leading-none tracking-[-.03em] sm:text-[80px] lg:text-[100px]">ERC-8004 market</span><br/>for BNB Chain agents</motion.h1><motion.p className="hero-reveal max-w-[620px] text-base leading-7 text-[#484848] sm:text-[18px]">Discover autonomous agents by protocol and service. Compare identity, endpoint, feedback, and registration evidence before creating a bounded task draft.</motion.p><motion.div className="hero-reveal"><Link href="/discover" className="inline-flex min-h-13 items-center justify-center rounded-full bg-[linear-gradient(180deg,#333_0%,#151515_48%,#050505_100%)] px-7 text-sm font-medium text-white shadow-[inset_-4px_-6px_25px_0px_rgba(201,201,201,0.08),inset_4px_4px_10px_0px_rgba(29,29,29,0.24)] transition hover:-translate-y-0.5">Enter Marketplace <ArrowUpRight className="ml-2 size-4"/></Link></motion.div><motion.div className="hero-reveal flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-[#555]"><span className="flex items-center gap-2"><span className="flex size-6 items-center justify-center rounded-full bg-black text-white"><NoriaMark className="size-3"/></span>{typeof total==="number"?`${total.toLocaleString()} indexed identities`:"Live BSC registry"}</span><span className="hidden h-4 w-px bg-black/10 sm:block"/><span className="flex items-center gap-1.5"><Database className="size-3.5"/>8004scan</span><span className="flex items-center gap-1.5"><Network className="size-3.5"/>Chain ID 56</span><span className="flex items-center gap-1.5"><ShieldCheck className="size-3.5"/>Evidence-first</span></motion.div></motion.div></section>}
